### ISSUE TITLE
Exception while looking for files

### ISSUE THREAD

**Issue by sTiKyt** [broderickhyman/albiondata-bin-dumper#1]
```
#---- Starting Extraction Operation ----#
Extracting .\game\Albion-Online_Data\StreamingAssets\GameData\localization.bin...
Unhandled exception. System.IO.FileNotFoundException: Could not find file '/home/nameless/Documents/AlbionOnlineGameData/Albion Online/.\game\Albion-Online_Data\StreamingAssets\GameData\localization.bin'.
File name: '/home/nameless/Documents/AlbionOnlineGameData/Albion Online/.\game\Albion-Online_Data\StreamingAssets\GameData\localization.bin'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Extractor.Extractors.BinaryDecrypter.DecryptBinaryFile(String inputPath, Stream outputStream)
   at Extractor.Extractors.BaseExtractor.DecryptBinFile(String binFile, String outputFolderPath)
   at Extractor.LocalizationData..ctor(String mainGameFolder, String outputFolderPath)
   at CommandLine.Program.RunExtractions()
   at CommandLine.Program.OnExecute()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at CommandLine.Program.Main(String[] args)
[1]    1735188 abort (core dumped)  ./CommandLine --main-game-folder  --output-folder-path ./Output/

```

There is no "\game\" folder, also on linux `/` is used instead of `\` in path, for example:
`/home/nameless/Documents/AlbionOnlineGameData/Albion Online/`

Please fix this

**Comment by sTiKyt** [comment]
Also i would like to have an option to provide path directly to "StreamingAssets/GameData" folder instead of going to game folder
